2017-02-03 20:29:35 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:29:35 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:23 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:23 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:48 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:48 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:49 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:49 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:49 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:49 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:50 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:50 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:40 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:40 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:41 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:41 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:42 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:42 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:42 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:42 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:55 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:55 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:56 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:56 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:57 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:57 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:57 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:57 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:57 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:57 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:06:12 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:06:12 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:06:13 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:06:13 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:10 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:10 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:11 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:11 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:12 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:12 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:12 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:12 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:13:22 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:13:22 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:32:31 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\index.ctp, line 23]
2017-02-04 10:32:31 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:37:30 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\index.ctp, line 23]
2017-02-04 10:37:30 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:37:32 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\index.ctp, line 23]
2017-02-04 10:37:32 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:08:40 Error: [MissingActionException] Action NetsController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'NetsController',
  'action' => 'edit',
)
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#2 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-02-04 11:26:40 Error: Fatal Error (1): Call to a member function findById() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 20]
2017-02-04 11:26:40 Error: [FatalErrorException] Call to a member function findById() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:32:35 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:32:35 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:32:51 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:32:51 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:36:06 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:36:06 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:37:46 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:37:46 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:37:48 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:37:48 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:37:53 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:37:53 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:43:26 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:43:26 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:43:44 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:43:44 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:44:45 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:44:45 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:45:22 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:45:22 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:45:33 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:45:33 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:46:21 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:46:21 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 12:09:25 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 12:09:25 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 12:10:40 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 12:10:40 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:08:02 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:08:02 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:15:41 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:15:41 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:17:15 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:17:15 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:17:49 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:17:49 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 15:45:55 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-05 15:45:57 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-05 16:04:19 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 16:04:19 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 16:04:25 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 16:04:25 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:11:44 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:11:44 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:12:32 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:12:32 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:12:42 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:12:42 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:12:45 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:12:45 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 21:17:10 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(UsersController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(UsersController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-05 21:40:48 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(UsersController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(UsersController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-05 21:40:52 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(UsersController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(UsersController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-05 21:41:58 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(NetsController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(NetsController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-06 14:26:29 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:26:36 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:26:55 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:26:56 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:34 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:49 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:49 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:50 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:55 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:29:00 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:59:14 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:59:15 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:03:40 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:03:56 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:08:07 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:08:10 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:11:03 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:11:56 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:12:06 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:20:06 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:20:48 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\cake\app\View\Elements\menu.ctp, line 24]
2017-02-06 15:20:48 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /cake/iptvs
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:06:24 Error: Fatal Error (4): syntax error, unexpected 'id' (T_STRING), expecting ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:06:24 Error: [FatalErrorException] syntax error, unexpected 'id' (T_STRING), expecting ')'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:07:05 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:07:05 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:07:44 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:07:44 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:30 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:08:30 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:32 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:08:32 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:44 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 19]
2017-02-24 21:08:44 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:45 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 19]
2017-02-24 21:08:45 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:45 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 19]
2017-02-24 21:08:45 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:11:06 Error: Fatal Error (4): syntax error, unexpected 'debug' (T_STRING) in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 17]
2017-02-24 21:11:06 Error: [FatalErrorException] syntax error, unexpected 'debug' (T_STRING)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:11:07 Error: Fatal Error (4): syntax error, unexpected 'debug' (T_STRING) in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 17]
2017-02-24 21:11:07 Error: [FatalErrorException] syntax error, unexpected 'debug' (T_STRING)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:11:57 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 20]
2017-02-24 21:11:57 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:18:32 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 21]
2017-02-24 21:18:32 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:19:27 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 21]
2017-02-24 21:19:27 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:19:28 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 21]
2017-02-24 21:19:28 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:19:47 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 20]
2017-02-24 21:19:47 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-25 21:53:04 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 27]
2017-02-25 21:53:04 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-25 21:59:12 Error: [NotFoundException] Такого пользователя нет!
Request URL: /cake/nets/edit
Stack Trace:
#0 [internal function]: NetsController->edit()
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(NetsController), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#4 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2017-02-25 22:16:12 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\admin_index.ctp, line 25]
2017-02-25 22:16:12 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-25 22:16:12 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\admin_index.ctp, line 25]
2017-02-25 22:16:12 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:30:30 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 19]
2017-03-05 12:30:30 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:30:39 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 19]
2017-03-05 12:30:39 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:30:53 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 19]
2017-03-05 12:30:53 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:31:26 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 25]
2017-03-05 12:31:26 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:31:30 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 25]
2017-03-05 12:31:30 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:48:36 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 39]
2017-03-05 12:48:36 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 39)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 39, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 39, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 19:50:53 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-05 19:50:53 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:01:01 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-09 20:01:01 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:11:27 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:11:27 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:11:35 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:11:35 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:12:44 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:12:44 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:17:24 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:17:24 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:19:16 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:19:16 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:25:08 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 72]
2017-03-09 20:25:08 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:17:34 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 72]
2017-03-09 21:17:34 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:44:03 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:44:03 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:44:05 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:44:05 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:44:08 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:44:08 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:11 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:11 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:13 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:13 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:13 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:13 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:16 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:16 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:24 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 91]
2017-03-09 21:45:24 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:26 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 91]
2017-03-09 21:45:26 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:10 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:10 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:13 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:13 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:23 Error: Fatal Error (4): syntax error, unexpected '*', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:23 Error: [FatalErrorException] syntax error, unexpected '*', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:24 Error: Fatal Error (4): syntax error, unexpected '*', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:24 Error: [FatalErrorException] syntax error, unexpected '*', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:25 Error: Fatal Error (4): syntax error, unexpected '*', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:25 Error: [FatalErrorException] syntax error, unexpected '*', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:41 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:41 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:13 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:13 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:14 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:14 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:27 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:27 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:28 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:28 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:49:10 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:49:10 Error: [FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:49:11 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:49:11 Error: [FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:49:11 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:49:11 Error: [FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
