2017-02-03 20:29:35 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:29:35 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:23 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:23 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:48 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:48 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:49 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:49 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:49 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:49 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:30:50 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:30:50 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:40 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:40 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:41 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:41 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:42 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:42 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:42 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:42 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:55 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:55 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:56 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:56 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:57 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:57 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:57 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:57 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-03 20:31:57 Error: Fatal Error (1): Call to undefined function set() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 10]
2017-02-03 20:31:57 Error: [FatalErrorException] Call to undefined function set()
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:20 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:20 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:21 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:21 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:50 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:50 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:51 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:51 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:05:52 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:05:52 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:06:12 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:06:12 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:06:13 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:06:13 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:10 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:10 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:11 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:11 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:12 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:12 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:10:12 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:10:12 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:13:22 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 11]
2017-02-04 10:13:22 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:32:31 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\index.ctp, line 23]
2017-02-04 10:32:31 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:37:30 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\index.ctp, line 23]
2017-02-04 10:37:30 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 10:37:32 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\index.ctp, line 23]
2017-02-04 10:37:32 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 23, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:08:40 Error: [MissingActionException] Action NetsController::edit() could not be found.
Exception Attributes: array (
  'controller' => 'NetsController',
  'action' => 'edit',
)
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#2 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-02-04 11:26:40 Error: Fatal Error (1): Call to a member function findById() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 20]
2017-02-04 11:26:40 Error: [FatalErrorException] Call to a member function findById() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:32:35 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:32:35 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:32:51 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:32:51 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:36:06 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:36:06 Error: [FatalErrorException] syntax error, unexpected '{'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:37:46 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:37:46 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:37:48 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:37:48 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:37:53 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 25]
2017-02-04 11:37:53 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:43:26 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:43:26 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:43:44 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:43:44 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:44:45 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:44:45 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:45:22 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:45:22 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:45:33 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:45:33 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 11:46:21 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 11:46:21 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 12:09:25 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 12:09:25 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 12:10:40 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 12:10:40 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:08:02 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:08:02 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:15:41 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:15:41 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:17:15 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:17:15 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-04 14:17:49 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 26]
2017-02-04 14:17:49 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /cake/nets/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 26, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 15:45:55 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-05 15:45:57 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-05 16:04:19 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 16:04:19 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 16:04:25 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 16:04:25 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:11:44 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:11:44 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:12:32 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:12:32 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:12:42 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:12:42 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 19:12:45 Error: Fatal Error (1): Call to a member function allow() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 9]
2017-02-05 19:12:45 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-05 21:17:10 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(UsersController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(UsersController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-05 21:40:48 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(UsersController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(UsersController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-05 21:40:52 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(UsersController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(UsersController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-05 21:41:58 Error: [CakeException] $controller does not implement an isAuthorized() method.
Request URL: /cake/nets
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\Auth\BaseAuthorize.php(72): ControllerAuthorize->controller(Object(NetsController))
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(502): BaseAuthorize->__construct(Object(ComponentCollection), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(464): AuthComponent->constructAuthorize()
#3 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\AuthComponent.php(310): AuthComponent->isAuthorized(Array)
#4 [internal function]: AuthComponent->startup(Object(NetsController))
#5 C:\xampp\htdocs\cake\lib\Cake\Utility\ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 C:\xampp\htdocs\cake\lib\Cake\Event\CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(189): Controller->startupProcess()
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-02-06 14:26:29 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:26:36 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:26:55 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:26:56 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:34 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:49 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:49 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:50 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:28:55 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:29:00 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:59:14 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 14:59:15 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:03:40 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:03:56 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:08:07 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:08:10 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:11:03 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:11:56 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:12:06 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:20:06 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-02-06 15:20:48 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\cake\app\View\Elements\menu.ctp, line 24]
2017-02-06 15:20:48 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /cake/iptvs
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:06:24 Error: Fatal Error (4): syntax error, unexpected 'id' (T_STRING), expecting ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:06:24 Error: [FatalErrorException] syntax error, unexpected 'id' (T_STRING), expecting ')'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:07:05 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:07:05 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:07:44 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:07:44 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:30 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:08:30 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:32 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 18]
2017-02-24 21:08:32 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:44 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 19]
2017-02-24 21:08:44 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:45 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 19]
2017-02-24 21:08:45 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:08:45 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 19]
2017-02-24 21:08:45 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:11:06 Error: Fatal Error (4): syntax error, unexpected 'debug' (T_STRING) in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 17]
2017-02-24 21:11:06 Error: [FatalErrorException] syntax error, unexpected 'debug' (T_STRING)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:11:07 Error: Fatal Error (4): syntax error, unexpected 'debug' (T_STRING) in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 17]
2017-02-24 21:11:07 Error: [FatalErrorException] syntax error, unexpected 'debug' (T_STRING)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:11:57 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 20]
2017-02-24 21:11:57 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:18:32 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 21]
2017-02-24 21:18:32 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:19:27 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 21]
2017-02-24 21:19:27 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:19:28 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 21]
2017-02-24 21:19:28 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 21, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-24 21:19:47 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 20]
2017-02-24 21:19:47 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-25 21:53:04 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 27]
2017-02-25 21:53:04 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-25 21:59:12 Error: [NotFoundException] Такого пользователя нет!
Request URL: /cake/nets/edit
Stack Trace:
#0 [internal function]: NetsController->edit()
#1 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(NetsController), Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#4 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2017-02-25 22:16:12 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\admin_index.ctp, line 25]
2017-02-25 22:16:12 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-02-25 22:16:12 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [C:\xampp\htdocs\cake\app\View\Nets\admin_index.ctp, line 25]
2017-02-25 22:16:12 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:30:30 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 19]
2017-03-05 12:30:30 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:30:39 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 19]
2017-03-05 12:30:39 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:30:53 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 19]
2017-03-05 12:30:53 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:31:26 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 25]
2017-03-05 12:31:26 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:31:30 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 25]
2017-03-05 12:31:30 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 12:48:36 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 39]
2017-03-05 12:48:36 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 39)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 39, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 39, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-05 19:50:53 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-05 19:50:53 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:01:01 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-09 20:01:01 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:11:27 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:11:27 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:11:35 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:11:35 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:12:44 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:12:44 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:17:24 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:17:24 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:19:16 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 70]
2017-03-09 20:19:16 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 70, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 20:25:08 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 72]
2017-03-09 20:25:08 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:17:34 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 72]
2017-03-09 21:17:34 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 72, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:44:03 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:44:03 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:44:05 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:44:05 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:44:08 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:44:08 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:11 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:11 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:13 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:13 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:13 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:13 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:16 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 76]
2017-03-09 21:45:16 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 76, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:24 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 91]
2017-03-09 21:45:24 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:45:26 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 91]
2017-03-09 21:45:26 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 91, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:10 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:10 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:13 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:13 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:23 Error: Fatal Error (4): syntax error, unexpected '*', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:23 Error: [FatalErrorException] syntax error, unexpected '*', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:24 Error: Fatal Error (4): syntax error, unexpected '*', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:24 Error: [FatalErrorException] syntax error, unexpected '*', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:25 Error: Fatal Error (4): syntax error, unexpected '*', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:25 Error: [FatalErrorException] syntax error, unexpected '*', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:47:41 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:47:41 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:13 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:13 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:14 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:14 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:27 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:27 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:48:28 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:48:28 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:49:10 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:49:10 Error: [FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:49:11 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:49:11 Error: [FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-09 21:49:11 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 68]
2017-03-09 21:49:11 Error: [FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 68, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-10 10:17:52 Error: Fatal Error (4): syntax error, unexpected 'for' (T_FOR) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 80]
2017-03-10 10:17:52 Error: [FatalErrorException] syntax error, unexpected 'for' (T_FOR)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-10 10:18:58 Error: Fatal Error (4): syntax error, unexpected 'for' (T_FOR) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 80]
2017-03-10 10:18:58 Error: [FatalErrorException] syntax error, unexpected 'for' (T_FOR)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-12 13:15:12 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-12 13:15:12 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-12 13:20:22 Error: Fatal Error (4): syntax error, unexpected 'for' (T_FOR) in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 80]
2017-03-12 13:20:22 Error: [FatalErrorException] syntax error, unexpected 'for' (T_FOR)
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-12 14:34:05 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 91]
2017-03-12 14:34:05 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 91)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 91, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 91, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-19 14:37:24 Error: Fatal Error (4): syntax error, unexpected end of file in [C:\xampp\htdocs\cake\app\View\Bids\admin_index.ctp, line 32]
2017-03-19 14:37:24 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-19 15:51:12 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cake\app\Controller\BidsController.php, line 108]
2017-03-19 15:51:12 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 108)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 108, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 108, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 11:31:52 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-21 11:31:52 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 11:32:10 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-21 11:32:10 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 11:32:59 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-21 11:32:59 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 11:33:51 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-21 11:33:51 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 12:03:27 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 45]
2017-03-21 12:03:27 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 12:05:34 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\cake\app\View\Bids\user_index.ctp, line 15]
2017-03-21 12:05:34 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-21 12:05:39 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\cake\app\View\Bids\user_index.ctp, line 15]
2017-03-21 12:05:39 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /cake/bids
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-26 15:48:42 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`cake_dip`.`nets`, CONSTRAINT `nets_ibfk_1` FOREIGN KEY (`net_id`) REFERENCES `users` (`net_id`) ON DELETE CASCADE ON UPDATE CASCADE)
Request URL: /cake/users/add
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `ca...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ca...')
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(1928): DboSource->create(Object(User), Array, Array)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 C:\xampp\htdocs\cake\app\Controller\UsersController.php(32): Model->save(Array)
#6 [internal function]: UsersController->add()
#7 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#10 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2017-03-30 21:48:33 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\TelsController.php, line 25]
2017-03-30 21:48:33 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/tels
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 21:48:36 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\VideosController.php, line 25]
2017-03-30 21:48:36 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/videos
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 22:14:48 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\TelsController.php, line 25]
2017-03-30 22:14:48 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/tels
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 22:39:25 Error: [MissingControllerException] Controller class StatController could not be found.
Exception Attributes: array (
  'class' => 'StatController',
  'plugin' => NULL,
)
Request URL: /cake/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-03-30 22:39:51 Error: [MissingControllerException] Controller class StatController could not be found.
Exception Attributes: array (
  'class' => 'StatController',
  'plugin' => NULL,
)
Request URL: /cake/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-03-30 22:44:42 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 99]
2017-03-30 22:44:42 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 99)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 99, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 99, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 22:49:10 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 102]
2017-03-30 22:49:10 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 102)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 102, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 102, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 22:49:28 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 103]
2017-03-30 22:49:28 Error: [FatalErrorException] syntax error, unexpected '='
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 103)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 103, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 103, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 22:49:30 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 103]
2017-03-30 22:49:30 Error: [FatalErrorException] syntax error, unexpected '='
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 103)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 103, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 103, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 23:34:54 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 7]
2017-03-30 23:34:54 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 23:45:35 Error: Fatal Error (4): syntax error, unexpected '=', expecting ',' or ';' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 15]
2017-03-30 23:45:35 Error: [FatalErrorException] syntax error, unexpected '=', expecting ',' or ';'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 23:52:48 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 9]
2017-03-30 23:52:48 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-30 23:52:59 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 9]
2017-03-30 23:52:59 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-31 20:56:34 Error: Fatal Error (4): syntax error, unexpected '==' (T_IS_EQUAL) in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 8]
2017-03-31 20:56:34 Error: [FatalErrorException] syntax error, unexpected '==' (T_IS_EQUAL)
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-31 20:56:47 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 8]
2017-03-31 20:56:47 Error: [FatalErrorException] syntax error, unexpected '='
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-31 20:56:49 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 8]
2017-03-31 20:56:49 Error: [FatalErrorException] syntax error, unexpected '='
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-31 21:02:19 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 37]
2017-03-31 21:02:19 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-03-31 22:04:31 Error: Fatal Error (1): Cannot use string offset as an array in [C:\xampp\htdocs\cake\app\View\Nets\stat.ctp, line 10]
2017-03-31 22:04:31 Error: [FatalErrorException] Cannot use string offset as an array
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Cannot use stri...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Cannot use stri...', 'C:\\xampp\\htdocs...', 10, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Cannot use stri...', 'C:\\xampp\\htdocs...', 10, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 12:33:49 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 114]
2017-04-03 12:33:49 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 114)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 114, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 114, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 12:34:21 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 114]
2017-04-03 12:34:21 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 114)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 114, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 114, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 12:47:41 Error: Fatal Error (1): Call to undefined function SUM() in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 114]
2017-04-03 12:47:41 Error: [FatalErrorException] Call to undefined function SUM()
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 114)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 114, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 114, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 12:52:01 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Model.cost' in 'field list'
Request URL: /cake/nets/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`b...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`b...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`b...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\app\Controller\NetsController.php(114): Model->find('all', Array)
#7 [internal function]: NetsController->stat()
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(NetsController), Array)
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(NetsController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-04-03 14:20:20 Error: Fatal Error (1): Unsupported operand types in [C:\xampp\htdocs\cake\app\Controller\TelsController.php, line 25]
2017-04-03 14:20:20 Error: [FatalErrorException] Unsupported operand types
Request URL: /cake/tels
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Unsupported ope...', 'C:\\xampp\\htdocs...', 25, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 16:33:57 Error: Fatal Error (4): syntax error, unexpected '?>', expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\TelsController.php, line 96]
2017-04-03 16:33:57 Error: [FatalErrorException] syntax error, unexpected '?>', expecting function (T_FUNCTION)
Request URL: /cake/tels/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 96)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 96, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 96, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 16:34:47 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\TelsController.php, line 95]
2017-04-03 16:34:47 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /cake/tels/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 95)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 95, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 95, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 16:34:48 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\cake\app\Controller\TelsController.php, line 95]
2017-04-03 16:34:48 Error: [FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION)
Request URL: /cake/tels/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 95)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 95, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 95, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-03 16:35:41 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Net.bill' in 'field list'
Request URL: /cake/tels/stat
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT sum(`Net...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT sum(`Net...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT sum(`Net...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Tel), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\app\Controller\TelsController.php(81): Model->find('all', Array)
#7 [internal function]: TelsController->stat()
#8 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TelsController), Array)
#9 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(TelsController), Object(CakeRequest))
#11 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-04-19 21:34:55 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1049] Unknown database \'cake_dip\'',
  'enabled' => true,
)
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\xampp\htdocs\cake\lib\Cake\Model\ConnectionManager.php(105): DboSource->__construct(Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3617): ConnectionManager::getDataSource('default')
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(1155): Model->setDataSource('default')
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3644): Model->setSource('users')
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(1387): Model->getDataSource()
#6 C:\xampp\htdocs\cake\lib\Cake\View\Helper\FormHelper.php(215): Model->schema()
#7 C:\xampp\htdocs\cake\lib\Cake\View\Helper\FormHelper.php(468): FormHelper->_introspectModel('User', 'fields')
#8 C:\xampp\htdocs\cake\app\View\Users\login.ctp(5): FormHelper->create('User')
#9 C:\xampp\htdocs\cake\lib\Cake\View\View.php(961): include('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\cake\lib\Cake\View\View.php(923): View->_evaluate('C:\\xampp\\htdocs...', Array)
#11 C:\xampp\htdocs\cake\lib\Cake\View\View.php(473): View->_render('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#13 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#14 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2017-04-20 08:38:47 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cake\app\View\Layouts\default.ctp, line 17]
2017-04-20 08:38:47 Error: [FatalErrorException] syntax error, unexpected ','
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-20 10:16:14 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-04-20 10:33:46 Error: [MissingActionException] Action TelsController::pay() could not be found.
Exception Attributes: array (
  'controller' => 'TelsController',
  'action' => 'pay',
)
Request URL: /cake/tels/pay/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(TelsController), Object(CakeRequest))
#2 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-04-20 12:20:57 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-04-20 12:30:42 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\cake\app\View\Nets\user_index.ctp, line 16]
2017-04-20 12:30:42 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 16, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 16, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-20 12:34:10 Error: Fatal Error (1): Call to a member function exists() on null in [C:\xampp\htdocs\cake\app\Controller\NetsController.php, line 122]
2017-04-20 12:34:10 Error: [FatalErrorException] Call to a member function exists() on null
Request URL: /cake/nets/pay/1
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 122)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 122, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 122, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-24 11:59:35 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-04-24 11:59:52 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-04-24 12:01:41 Error: [MissingControllerException] Controller class CakeController could not be found.
Exception Attributes: array (
  'class' => 'CakeController',
  'plugin' => NULL,
)
Request URL: /cake/cake/
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-04-27 12:42:16 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 46]
2017-04-27 12:42:16 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 46)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 46, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 46, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-27 12:43:27 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 46]
2017-04-27 12:43:27 Error: [FatalErrorException] Call to a member function error() on null
Request URL: /cake/users/login
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 46)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 46, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 46, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-04-27 19:09:37 Error: [MissingControllerException] Controller class NetController could not be found.
Exception Attributes: array (
  'class' => 'NetController',
  'plugin' => NULL,
)
Request URL: /cake/net
Stack Trace:
#0 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-04-29 13:45:19 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:46:17 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:47:40 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:47:50 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:49:36 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:49:44 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:50:01 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:51:56 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:52:00 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:53:15 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:54:14 Error: [MissingModelException] all
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate('all')
#1 [internal function]: UsersController->index()
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2017-04-29 13:54:58 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(40): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:56:50 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(40): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:58:04 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(40): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:58:14 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User' in 'where clause'
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Net`.`i...', Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(668): DboSource->execute('SELECT `Net`.`i...', Array, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Net`.`i...', false)
#4 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(3022): DboSource->read(Object(Net), Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\xampp\htdocs\cake\app\Controller\UsersController.php(40): PaginatorComponent->paginate(Array)
#8 [internal function]: UsersController->index()
#9 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2017-04-29 13:59:43 Error: [MissingModelException] Users
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\app\Controller\UsersController.php(39): PaginatorComponent->paginate('Users')
#1 [internal function]: UsersController->index()
#2 C:\xampp\htdocs\cake\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\xampp\htdocs\cake\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\xampp\htdocs\cake\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2017-04-29 17:34:02 Error: Fatal Error (1): Call to undefined method PaginatorComponent::paginate1() in [C:\xampp\htdocs\cake\app\Controller\UsersController.php, line 39]
2017-04-29 17:34:02 Error: [FatalErrorException] Call to undefined method PaginatorComponent::paginate1()
Request URL: /cake/users/index/sort:id/direction:asc
Stack Trace:
#0 C:\xampp\htdocs\cake\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 39)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 39, Array)
#2 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 39, Array)
#3 C:\xampp\htdocs\cake\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
